Repository beyond-sw-camp/be12-fin-Catcher-GrapeField-BE, pull requests merged in 2025-04, with the labels that each got.

#18 [Feat/chat/init] WebSocket 초기 환경설정
  build.gradle
  src/main/java/com/example/grapefield/chat/controller/ChatController.java
  src/main/java/com/example/grapefield/chat/controller/ChatWebSocketController.java
  src/main/java/com/example/grapefield/chat/model/entity/ChatHighlight.java
  src/main/java/com/example/grapefield/chat/model/entity/ChatMessageArchive.java
  src/main/java/com/example/grapefield/chat/model/entity/ChatMessageBase.java
  src/main/java/com/example/grapefield/chat/model/entity/ChatMessageCurrent.java
  src/main/java/com/example/grapefield/chat/model/entity/ChatRoom.java
  src/main/java/com/example/grapefield/chat/model/entity/ChatroomMember.java
  src/main/java/com/example/grapefield/chat/model/request/ChatMessageKafkaReq.java
  src/main/java/com/example/grapefield/chat/model/request/ChatMessageReq.java
  src/main/java/com/example/grapefield/chat/model/response/ChatDetailResp.java
  src/main/java/com/example/grapefield/chat/model/response/ChatListResp.java
  src/main/java/com/example/grapefield/chat/model/response/ChatMessageItemResp.java
  src/main/java/com/example/grapefield/chat/model/response/ChatMessageResp.java
  src/main/java/com/example/grapefield/config/WebSocketConfig.java
  src/main/java/com/example/grapefield/events/model/entity/Events.java
  src/main/java/com/example/grapefield/user/model/entity/User.java
Labels: config, refactor

#49 feat/chat/merge
  docker-compose.yml
  src/main/java/com/example/grapefield/chat/config/KafkaConfig.java
  src/main/java/com/example/grapefield/chat/config/KafkaTopicConfig.java
  src/main/java/com/example/grapefield/chat/controller/ChatRoomMemberController.java
  src/main/java/com/example/grapefield/chat/controller/ChatTestController.java
  src/main/java/com/example/grapefield/chat/controller/ChatWebSocketController.java
  src/main/java/com/example/grapefield/chat/kafka/ChatKafkaConsumer.java
  src/main/java/com/example/grapefield/chat/kafka/ChatKafkaProducer.java
  src/main/java/com/example/grapefield/chat/model/entity/ChatroomMember.java
  src/main/java/com/example/grapefield/chat/repository/ChatMessageBaseRepository.java
  src/main/java/com/example/grapefield/chat/repository/ChatMessageCurrentRepository.java
  src/main/java/com/example/grapefield/chat/repository/ChatRoomMemberRepository.java
  src/main/java/com/example/grapefield/chat/repository/ChatRoomRepository.java
  src/main/java/com/example/grapefield/chat/service/ChatMessageService.java
  src/main/java/com/example/grapefield/chat/service/ChatRoomMemberService.java
  src/main/java/com/example/grapefield/chat/service/ChatRoomService.java
  src/main/java/com/example/grapefield/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: enhancement

#86 Feat/chat/merge 각종 채팅방 조회기능 및 채팅메세지 전송 저장 기능
  src/main/java/com/example/grapefield/chat/config/KafkaConfig.java
  src/main/java/com/example/grapefield/chat/controller/ChatRoomDetailController.java
  src/main/java/com/example/grapefield/chat/controller/ChatRoomListController.java
  src/main/java/com/example/grapefield/chat/controller/ChatRoomMemberController.java
  src/main/java/com/example/grapefield/chat/controller/ChatWebSocketController.java
  src/main/java/com/example/grapefield/chat/kafka/ChatKafkaConsumer.java
  src/main/java/com/example/grapefield/chat/kafka/ChatKafkaProducer.java
  src/main/java/com/example/grapefield/chat/model/request/ChatMessageKafkaReq.java
  src/main/java/com/example/grapefield/chat/model/response/ChatHighlightResp.java
  src/main/java/com/example/grapefield/chat/model/response/ChatListPageResp.java
  src/main/java/com/example/grapefield/chat/model/response/ChatListResp.java
  src/main/java/com/example/grapefield/chat/model/response/ChatMessageResp.java
  src/main/java/com/example/grapefield/chat/model/response/ChatRoomDetailResp.java
  src/main/java/com/example/grapefield/chat/model/response/ChatRoomMemberResp.java
  src/main/java/com/example/grapefield/chat/model/response/PopularChatRoomListResp.java
  src/main/java/com/example/grapefield/chat/repository/ChatHighlishtRepository.java
  src/main/java/com/example/grapefield/chat/repository/ChatMessageArchiveRepository.java
  src/main/java/com/example/grapefield/chat/repository/ChatMessageCurrentRepository.java
  src/main/java/com/example/grapefield/chat/repository/ChatRoomMemberRepository.java
  src/main/java/com/example/grapefield/chat/repository/ChatRoomRepository.java
  src/main/java/com/example/grapefield/chat/service/ChatMessageService.java
  src/main/java/com/example/grapefield/chat/service/ChatRoomListService.java
  src/main/java/com/example/grapefield/chat/service/ChatRoomMemberService.java
  src/main/java/com/example/grapefield/chat/service/ChatRoomService.java
  src/main/java/com/example/grapefield/config/SecurityConfig.java
Labels: enhancement

#89 Feat/chat/my room 코드 에러 수정
  src/main/java/com/example/grapefield/chat/controller/ChatRoomListController.java
  src/main/java/com/example/grapefield/chat/controller/ChatRoomMemberController.java
  src/main/java/com/example/grapefield/chat/service/ChatRoomListService.java
Labels: bug

#103 [feat/chat/jwt] 웹소켓 jwt 사용 - JwtHandshakeInterceptor 커스텀
  src/main/java/com/example/grapefield/chat/controller/ChatTestController.java
  src/main/java/com/example/grapefield/chat/controller/ChatWebSocketController.java
  src/main/java/com/example/grapefield/chat/model/request/ChatMessageReq.java
  src/main/java/com/example/grapefield/config/WebSocketConfig.java
  src/main/java/com/example/grapefield/config/websocket/CustomHandshakeHandler.java
  src/main/java/com/example/grapefield/config/websocket/JwtHandshakeInterceptor.java
Labels: enhancement

#111 [refactor] KafkaTopicService로 로직분리
  src/main/java/com/example/grapefield/chat/kafka/ChatKafkaConsumer.java
  src/main/java/com/example/grapefield/chat/kafka/HeartKafkaConsumer.java
  src/main/java/com/example/grapefield/chat/service/ChatRoomService.java
  src/main/java/com/example/grapefield/chat/service/KafkaTopicService.java
Labels: enhancement

#113 [refactor] 오타 수정
  src/main/java/com/example/grapefield/chat/controller/ChatWebSocketController.java
  src/main/java/com/example/grapefield/chat/kafka/HeartKafkaConsumer.java
Labels: bug

#119 [fix] 오류 수정 토픽 보장 및 생성 로직 순서 변경
  src/main/java/com/example/grapefield/chat/config/KafkaConfig.java
  src/main/java/com/example/grapefield/chat/kafka/ChatKafkaConsumer.java
  src/main/java/com/example/grapefield/chat/kafka/ChatKafkaProducer.java
  src/main/java/com/example/grapefield/chat/kafka/HeartKafkaConsumer.java
Labels: bug

#142 [fix] actuator 설정 변경
  build.gradle
  src/main/java/com/example/grapefield/config/ActuatorSecurityConfig.java
  src/main/java/com/example/grapefield/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: bug

#138 [chore] 주석제거 리팩토링
  src/main/java/com/example/grapefield/chat/kafka/ChatKafkaConsumer.java
  src/main/java/com/example/grapefield/chat/kafka/HeartKafkaConsumer.java
  src/main/java/com/example/grapefield/chat/service/ChatRoomService.java
  src/main/java/com/example/grapefield/chat/service/KafkaTopicService.java
Labels: refactor
